%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 573.3130
Camera.fy: 573.3899
Camera.cx: 321.0333
Camera.cy: 243.5320

Camera.k1: 0.1248
Camera.k2: -0.2051
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 10.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Transformation from camera to body-frame (odom) Tbc
# Tbc: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: f
#    data: [0.0, 0.0, -1.0, 0.07,
#           0.0, 1.0, 0.0, 0.0,
#           1.0, 0.0, 0.0, 0.185,
#           0.0, 0.0, 0.0, 1.0]
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.0, 1.0, 0.0, -0.07,
          -1.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0]

# Covariance for ODOM data
Cov: !!opencv-matrix
   rows: 6
   cols: 6
   dt: f
   data: [1e-9, 0.0, 0.0, 0.0, 0.0, 0.0, 
          0.0, 1e-3, 1e-9, 0.0, 0.0, 0.0, 
          0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 
          0.0, 0.0, 0.0, 1e6, 0.0, 0.0, 
          0.0, 0.0, 0.0, 0.0, 1e6, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 1e-9]

# ODOM noise
ODOM.Noise: 1e-3
ODOM.Frequency: 20


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 500

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 2.0

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 3

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 19
ORBextractor.minThFAST: 11

# new add. 0-ORB, 1-GFTT, 2-SURF
ORBextractor.nFeatureType: 0

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

