%YAML:1.0

#### Settings for my dataset, revise for specific dataset accordingly. #####

# Tracking frequency
fps: 10

# How many images, start and max
img_start_idx: 0
img_count: 3106

# Accepted feature depth bounds [mm]
upper_depth: 5000.0
lower_depth: 1000.0

# For lose detection
max_linear_speed: 1000     # 2000 mm/s
max_angular_speed: 100    # 200 degree/s

# For feature detection
scale_factor: 2   # > 1
feature_sigma: 0.5  # useless for now
max_level: 3        # 1 level for upward camera
max_feature_num: 500

# For local graph (unit: m)
max_local_frame_num: 20         # 10
local_frame_search_level: 3     # 1
local_frame_search_radius: 3    # 0.3

# For global map loopclose
gm_vcl_num_min_match_mp: 12
gm_vcl_num_min_match_kp: 24
gm_vcl_ratio_min_match_kp: 0.05
gm_dcl_min_kfid_offset: 20
gm_dcl_min_score_best: 0.05

# Optimization
## Robust kernel for 2d MapPoint constraint
th_huber2: 5.991
## How many loops in optimizer iteration
local_iter: 15
global_iter: 20
## 1 for print debug info, 0 for not
local_print: 0
global_print: 0

# For odometry uncertainty
odo_x_uncertain: 0.01
odo_y_uncertain: 0.01
odo_theta_uncertain: 0.01

# For odometry noise (in a moment) (unit: mm, rad)
odo_x_steady_noise: 1
odo_y_steady_noise: 1
odo_theta_steady_noise: 0.005

# For plane motion constraint
plane_motion_xrot_info: 1e6
plane_motion_yrot_info: 1e6
plane_motion_z_info: 1


# For map storage
## 1 if use previously saved map, 0 if not
use_prev_map: 0
## 1 if save map when exit, o if not
save_new_map: 0
## 1 if disable SLAM and do localization only (use_prev_map must be 1), 0 if do SLAM
localization_only: 0
## map file config
map_file_store_path: "/home/vance/output/se2/map/"
read_map_file_name: "se2.map"
write_map_file_name: "se2.map"
write_traj_file_name: "se2.traj"

# For visulization
need_visulization: 1    # if 0, images will not be saved.
mappub_scale_ratio: 300
camera_size: 0.3
point_size: 0.1

# For debug
## 1 for verbose, 0 for non-verbose
local_verbose: 0
global_verbose: 0

#show_ground_truth: 1
save_match_image: 0
match_image_store_path: "/home/vance/output/se2lam/match/"
